import{a as y,S as v,i}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const w="47458933-146f1ea8ad921328f8e999f88",L="https://pixabay.com/api/",S=15;async function u(o,t=1){const a={key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:S};try{return(await y.get(L,{params:a})).data}catch{toggleLoader(!1),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}}function f(o){const t=document.querySelector("#gallery"),a=o.map(({webformatURL:s,largeImageURL:e,tags:r,likes:n,views:p,comments:m,downloads:h})=>`
                 <li> <a href="${e}">
                <img src="${s}" alt="${r}" width="360px" height="200px" class="image"/>
                </a>
                <div class = "info">
                <div class="info-div"> <p class="section"> Likes: </p> <p class="result" > ${n} </p> </div>
                <div class="info-div"> <p class="section"> Views: </p> <p class="result"> ${p} </p> </div>
                <div class="info-div"> <p class="section"> Comments: </p> <p class="result"> ${m} </p> </div>
                <div class="info-div"> <p class="section"> Downloads: </p> <p class="result"> ${h} </p> </div>
                 </div>
                </li>
               `).join("");t.insertAdjacentHTML("beforeend",a)}function P(){gallery.innerHTML=""}function c(o){document.querySelector("#toggle-div").classList.toggle("hidden",!o)}function d(o){document.querySelector("#load-more").classList.toggle("hidden",!o)}const E=document.querySelector("#search-form"),g=document.querySelector("#search-input"),q=document.querySelector("#load-more"),b=15;let l=1;const $=new v("#gallery a",{captionsData:"alt",captionDelay:250});E.addEventListener("submit",async o=>{o.preventDefault();const t=g.value.trim();if(!t){i.error({title:"Error",message:"Search field cannot be empty!"});return}P(),d(!1),c(!0);const a=1;try{const s=await u(t,a);if(c(!1),!s.hits.length){i.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}f(s.hits),$.refresh(),a*15<s.totalHits&&d(!0)}catch{c(!1),i.error({title:"Error",message:"Something went wrong. Please try again later."})}});q.addEventListener("click",async()=>{const o=g.value.trim();l+=1;try{const t=await u(o,l);f(t.hits);const{height:a}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"}),l*b>=t.totalHits&&(d(!1),i.info({title:"End of Results",message:"We`re sorry, but you`ve reached the end of search results."}))}catch{c(!1),i.error({title:"Error",message:"Something went wrong. Please try again later."})}});
//# sourceMappingURL=index.js.map
