import{a as v,S as w,i as n}from"./assets/vendor-DEenWwFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const L="47458933-146f1ea8ad921328f8e999f88",S="https://pixabay.com/api/",P=15;async function u(o,e=1){const a={key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:P};try{return(await v.get(S,{params:a})).data}catch{toggleLoader(!1),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}}function d(o){const e=document.querySelector("#gallery"),a=o.map(({webformatURL:r,largeImageURL:t,tags:s,likes:i,views:h,comments:p,downloads:y})=>`
                 <li> <a href="${t}">
                <img src="${r}" alt="${s}" width="360px" height="200px" class="image"/>
                </a>
                <div class = "info">
                <div class="info-div"> <p class="section"> Likes: </p> <p class="result" > ${i} </p> </div>
                <div class="info-div"> <p class="section"> Views: </p> <p class="result"> ${h} </p> </div>
                <div class="info-div"> <p class="section"> Comments: </p> <p class="result"> ${p} </p> </div>
                <div class="info-div"> <p class="section"> Downloads: </p> <p class="result"> ${y} </p> </div>
                 </div>
                </li>
               `).join("");e.insertAdjacentHTML("beforeend",a)}function E(){gallery.innerHTML=""}function l(o){document.querySelector("#toggle-div").classList.toggle("hidden",!o)}function g(o){document.querySelector("#load-more").classList.toggle("hidden",!o)}const q=document.querySelector("#search-form"),m=document.querySelector("#search-input"),b=document.querySelector("#load-more"),$=15;let c=1;const f=new w("#gallery a",{captionsData:"alt",captionDelay:250});q.addEventListener("submit",async o=>{o.preventDefault();const e=m.value.trim();if(!e){n.error({title:"Error",message:"Search field cannot be empty!"});return}E(),g(!1),l(!0);const a=1;u(e).then(r=>{if(l(!1),!r.hits.length){n.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}d(r.hits),f.refresh()});try{const r=await u(e,a);if(l(!1),!r.hits.length){n.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}d(r.hits),f.refresh(),a*15<r.totalHits&&g(!0)}catch{l(!1),n.error({title:"Error",message:"Something went wrong. Please try again later."})}});b.addEventListener("click",async()=>{const o=m.value.trim();c+=1;try{const e=await u(o,c);d(e.hits);const{height:a}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"}),c*$>=e.totalHits&&(g(!1),n.info({title:"End of Results",message:"We`re sorry, but you`ve reached the end of search results."}))}catch{l(!1),n.error({title:"Error",message:"Something went wrong. Please try again later."})}});
//# sourceMappingURL=index.js.map
