import{a as v,S as w,i as l}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const L="47458933-146f1ea8ad921328f8e999f88",S="https://pixabay.com/api/",E=15;async function u(o,t=1){const s={key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:E};try{return(await v.get(S,{params:s})).data}catch{toggleLoader(!1),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}}function f(o){const t=document.querySelector("#gallery"),s=o.map(({webformatURL:a,largeImageURL:e,tags:r,likes:n,views:m,comments:h,downloads:y})=>`
                 <li> <a href="${e}">
                <img src="${a}" alt="${r}" width="360px" height="200px" class="image"/>
                </a>
                <div class = "info">
                <div class="info-div"> <p class="section"> Likes: </p> <p class="result" > ${n} </p> </div>
                <div class="info-div"> <p class="section"> Views: </p> <p class="result"> ${m} </p> </div>
                <div class="info-div"> <p class="section"> Comments: </p> <p class="result"> ${h} </p> </div>
                <div class="info-div"> <p class="section"> Downloads: </p> <p class="result"> ${y} </p> </div>
                 </div>
                </li>
               `).join("");t.insertAdjacentHTML("beforeend",s)}function P(){gallery.innerHTML=""}function c(o){document.querySelector("#toggle-div").classList.toggle("hidden",!o)}function d(o){document.querySelector("#load-more").classList.toggle("hidden",!o)}const q=document.querySelector("#search-form"),g=document.querySelector("#search-input"),b=document.querySelector("#load-more"),$=15;let i=1;const p=new w("#gallery a",{captionsData:"alt",captionDelay:250});q.addEventListener("submit",async o=>{o.preventDefault();const t=g.value.trim();if(!t){l.error({title:"Error",message:"Search field cannot be empty!"});return}P(),d(!1),c(!0),i=1;try{const s=await u(t,i);if(c(!1),!s.hits.length){l.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}f(s.hits),p.refresh(),i*15<s.totalHits&&d(!0)}catch{c(!1),l.error({title:"Error",message:"Something went wrong. Please try again later."})}});b.addEventListener("click",async()=>{const o=g.value.trim();i+=1;try{const t=await u(o,i);f(t.hits),p.refresh();const{height:s}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),i*$>=t.totalHits&&(d(!1),l.info({title:"End of Results",message:"We`re sorry, but you`ve reached the end of search results."}))}catch{c(!1),l.error({title:"Error",message:"Something went wrong. Please try again later."})}});
//# sourceMappingURL=index.js.map
